### ISSUE TITLE
Switching from DarkLight theme to original causes icon loading errors

### ISSUE THREAD

**Issue by kobuki** [crash0verride11/DarkLight-qBittorent-WebUI#10]
I'm using this theme in qbittorrent-nox 4.4.2 in a Docker container. All is working fine, but when I try to switch to the original theme via the sun/moon button, the toolbar icons and many others refuse to load, causing a HTTP 500 error with the following message: 

```Unacceptable file type, only regular file is allowed.```

I've installed the theme per the README.md instructions. Did I miss something?

**Comment by AgentConDier** [comment]
It seems to me those icons are missing entirely. The `Unacceptable file type...` message can also mean `404 Not Found`.

They probably used to be part of the qBittorrent default theme, but have been removed or renamed in a subsequent update. A light version of all the missing icons needs to be added to this repository, or the links changed to the new versions.

Also, if the peer country flags aren't working you may have missed the step in https://github.com/qbittorrent/qBittorrent/wiki/Developing-alternate-WebUIs-(WIP) to copy `/src/icons/*` from qBittorrent to `private/icons/`

**Comment by kobuki** [comment]
I switched to another dark skin as this one seems to be abandoned.
