### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by yodee13** [crash0verride11/DarkLight-qBittorent-WebUI#12]
After I apply the theme, with the icon size problem (issue #8) and general tab fix (issue #11) solution, i can't change the language. In the menu, and in the config file is the correct but WebUI is still in english...

![1](https://user-images.githubusercontent.com/112553334/202271783-2ceaeae7-0165-4965-a7c6-9a05ebe1f20c.jpg)
![2](https://user-images.githubusercontent.com/112553334/202271596-c94a746e-6b8b-44dd-9251-effeed024f69.jpg)

**Comment by crash0verride11** [comment]
I've tested and confirmed I repeat the same behavior, however it also occurs for me with the unedited source files from the qBittorrent GitHub master branch. As far as I can tell, it's a bug with qBittorrent and webUIs in general, though maybe others have found a fix for their UIs. 

**As a workaround** if you disable the alternate UI, change the language, and re-enable the alternate UI. The language will update correctly.

I can't seem to find the setting, file, or command that actually changes the interface language. I see the Locale preference updating in my config, similar to your screenshot, but that clearly is not enough. I'll investigate when I'm working on the project next.

**Comment by yodee13** [comment]
" As a workaround if you disable the alternate UI, change the language, and re-enable the alternate UI, then the language will update correctly."

Yes, this method is works. Unfortunetly till the first reboot...

**Comment by crash0verride11** [comment]
As discussed in another issue: #14. It appears the maintainers of qBittorrent have removed support for alternate webUI translations in general and alternate UI maintainers are expected to accommodate translation directly in their projects. I'll be keeping an eye on this to see if there is an easy way to do so, but this will sadly kill translation support for at least a while if not in general. In the latest version of qbittorrent (4.5.0) this completely breaks the UI for any language, including English.

**Comment by crash0verride11** [comment]
I've now removed the translation mechanism from this project entirely due to the removal of built-in for third-party webui translation support and to make the project useable on qBittorrent version 4.5.0+. I may add translation support in the future (unlikely for a while) and this project will sadly be English only for the foreseeable future.

**Comment by yodee13** [comment]
It works :) Thanks

**Comment by AgentConDier** [comment]
It seems server-side translation will return: https://github.com/qbittorrent/qBittorrent/pull/20711
Should be included in latest v4.6.5 version, but I haven't tested it yet.

**Comment by crash0verride11** [comment]
@AgentConDier I just tested with 4.6.5 and the www files from that release, and it does appear work, but you have to change language while the Alternate WebUI is disabled and then re-enable it. I also tested with the latest master branch files in the process and noticed there does appear to be a functional dark mode built-in as well. 

I will try to update for 4.6.5 in the next week and re-implement the language support. However, I'll probably be done with this project after that, considering the built-in dark mode coming and my diminishing use of the qBittorrent webUI. If you want to be added as a maintainer past that, I'm open to it. You're more active than anyone else here. I'll update the ReadMe for an open call for interest with the 4.6.5 update.

**Comment by AgentConDier** [comment]
Thanks for the update and your efforts so far! If the upstream dark mode is at least somewhat decent I'll probably switch to that in the future.
