### ISSUE TITLE
Add compatibility with v4.5.0

### ISSUE THREAD

**Issue by junpet** [crash0verride11/DarkLight-qBittorent-WebUI#14]

**Comment by AgentConDier** [comment]
Unfortunately, upstream decided to stop supporting translations in "3rd party" WebUIs, including the default one if it is loaded via the "Use alternate WebUI" option:
https://github.com/qbittorrent/qBittorrent/issues/18109#issuecomment-1332138714
So fixing the strings or even adding translation support now requires a lot of extra effort from everyone maintaining alternate WebUIs...

**Comment by crash0verride11** [comment]
Ooooph... that hurts. Truly will kill this project for a number of people I'm sure. I'll take a look at what other alternate webui options are doing (I use Vue Torrent for mobile and it loads as expected, I just prefer the standard webUI on desktop). I could possibly understand what they're doing and try to incorporate it into this project, but that is a big maybe on my end. 

It'll probably be some time before I get to even turning all the placeholder text into English to make it usable for myself. I'll be rolling back qbittorrent versions for now (or maybe even go back to the standard webUI and be blinded at night).

**Comment by 1RandomDev** [comment]
I think the missing translations aren't that big of a deal. I as a native German speaker have never even touched the language setting. It already would be a great fix if the texts would just be displayed currently in English since currently all menus show something like `QBT_TR(...)` which makes the webinterface completely unusable.

**Comment by espilioto** [comment]
Must agree, usually anyone tech savvy enough to do all this shouldn't have a problem with an English-only ui, I even switch all interfaces to English because it usually just makes way more sense than bad translations.

**Comment by crash0verride11** [comment]
I've added an [English only release](https://github.com/crash0verride11/DarkLight-qBittorent-WebUI/releases/tag/v0.3.1(Eng)). This project will be English only for the foreseeable future.

For anyone combining the DarkLight project files with the qBittorrent Master, the appropriate regex to fix the master files is `QBT_TR?\(` and `\)QBT_TR\[CONTEXT=.*?\]`
