### ISSUE TITLE
Transferlist horizontal scrollbar doesn't work properly

### ISSUE THREAD

**Issue by AgentConDier** [crash0verride11/DarkLight-qBittorent-WebUI#18]
Thank you for the release!
When I use the mouse to grab the horizontal scrollbar in the transferlist, the Panel container `#transferList` is scrolled instead of the actual table `#torrentsTableDiv`. Because of this, the table content is clipped:
![table-clipping](https://github.com/crash0verride11/DarkLight-qBittorent-WebUI/assets/27744962/e954ed8e-6b8a-44a9-b308-92f78af6fd16)
When using the middle mouse button to scroll, everything works as expected.

In the upstream webui, `#transferList` doesn't seem to allow horizontal scrolling, even though the `overflow: auto` style is identical. I haven't been able to find what the difference is. A workaround is to disable the offending overflow by adding the following line to the [Transfer List Panel options in client.js](https://github.com/crash0verride11/DarkLight-qBittorent-WebUI/blob/fdd0a2fa9f926bc90ce0274aec93d79c58853e34/private/scripts/client.js#L1235):
```
scrollbars: false
```

Browser: Firefox 115.3.0esr with "Always show scroll bars" disabled
OS: Debian 12, Kernel 6.1.0-13-amd64
qBittorrent: v4.5.5

**Comment by crash0verride11** [comment]
I noticed it intermittently (usually don't overflow), but thank you for pinning down specifically.

Adding the option into client.js is probably more elegant, but I prefer to keep as many overrides as possible in the sass/css. I've updated the dynamicTable.css.
