### ISSUE TITLE
Can't install on 4.1.5

### ISSUE THREAD

**Issue by JacopoMolteni** [crash0verride11/DarkLight-qBittorent-WebUI#2]
UI not working after trying to install this theme on 4.1.5, even if downloading the right version from the qbittorrent master

**Comment by crash0verride11** [comment]
Does the master Alternate webui work for you (without any of my files)? 

If it does, I'll try making a docker of an older qBitTorrent this week and seeing where the conflict is. Also what browser(s) are you using?

**Comment by JacopoMolteni** [comment]
With only the master alternate WebUI i get a functional interface (the blank spaces are edited for privacy):
![Screenshot from 2020-11-14 20-03-05](https://user-images.githubusercontent.com/16439736/99155103-5744e100-26b5-11eb-8334-b468db14b961.png)

With your files added I get this on Firefox (82.0.3):
![Screenshot from 2020-11-14 20-05-30](https://user-images.githubusercontent.com/16439736/99155129-8ce9ca00-26b5-11eb-8caf-33149c20bb7a.png)

While I get this on Chromium (86.0.4240.198):
![Screenshot from 2020-11-14 20-06-25](https://user-images.githubusercontent.com/16439736/99155151-b4409700-26b5-11eb-855f-79efba3accb2.png)

**Comment by crash0verride11** [comment]
Well it certainly seems like the Master is either not being "installed" correctly (none of the icons are loading besides the search icon for some extra strange reason) or is partially incompatible with 4.1.5, though clearly functional. Which most of what my code does is replace images, so I'm not too surprised it doesn't work right if none of the images are loading in the master. Also strange more of the icons seem to work with Chrome/my webUI files. 

I'll try loading a 4.1.5 version and seeing if I can reproduce your results when I have time. I wouldn't be surprised if it's just partially incompatible with the older version though. It seems like it's not uncommon for there to be bugs/glitches in the Master Alternate WebUI and even the latest versions of qbittorrent. The search/RSS tabs were broken until recently.

**Comment by JacopoMolteni** [comment]
Got it. Thanks for the help. I tried taking the master theme from the source of the 4.1.5 release, so that one should be compatible

**Comment by crash0verride11** [comment]
I finally got around to testing this on 4.1.5.9. Though above it looks like you didn't pull your the icons into the master alternative UI (the icons folder is not within the www private and public folders within the source code)

**Comment by JacopoMolteni** [comment]
I understand, thanks for the help.
