### ISSUE TITLE
WEBUI How to install a theme on qbittorrent?

### ISSUE THREAD

**Issue by C0la149** [crash0verride11/DarkLight-qBittorent-WebUI#32]
Hello everyone, please help me understand qbittorrent-nox. how to download and install the theme correctly? Can you provide instructions or a video that will show you step by step how to install the theme correctly? Thanks in advance for your answer.

**Comment by OdinVex** [comment]
> Hello everyone, please help me understand qbittorrent-nox. how to download and install the theme correctly? Can you provide instructions or a video that will show you step by step how to install the theme correctly? Thanks in advance for your answer.

Read the documentation from qBittorrent: https://github.com/qbittorrent/qBittorrent/wiki/Alternate-WebUI-usage

Recommend closing thread, should have read the manual.
