### ISSUE TITLE
RSS items colour in dark mode

### ISSUE THREAD

**Issue by aussiehuddo** [crash0verride11/DarkLight-qBittorent-WebUI#7]
Any possibility to change the font colour of new items in the RSS feeds from the dark blue as this is very difficult to read when on dark mode.

**Comment by crash0verride11** [comment]
https://github.com/crash0verride11/DarkLight-qBittorent-WebUI/blob/master/private/css/style.css

The revised CSS here should fix RSS tab issues. Don't forget to clear your cache for the website if you don't see any changes.

**Comment by aussiehuddo** [comment]
that makes it better. What is the corresponding value for this? would like to customise it myself. Maybe if new items text was light blue would be perfect.

**Comment by crash0verride11** [comment]
Feel free to customize. Color is defined under the class ".unreadArticle". If you want it to change for light/dark, you'll have to create a new variable and define it in several places (.light-theme, .dark-theme, prefers-color scheme: light, prefers-color scheme: dark)
