### ISSUE TITLE
Ginormous menu item icons

### ISSUE THREAD

**Issue by Barina** [crash0verride11/DarkLight-qBittorent-WebUI#8]
Menu items have a gigantic icons and in some menues (View) it overflows outside of visible are (goes bigger than the page) as shown in the image below.
![Screenshot 2022-04-20 182959](https://user-images.githubusercontent.com/370379/164268094-5f630f7c-3f6b-4d10-99e4-a5fd107aec1b.png)

**Comment by crash0verride11** [comment]
I'm guessing you're using Google Chrome for your browser or one of it's forks (as I've seen sizing related issues), but if you want to confirm what web browser (+ version number if possible) and operating system you're using (+ version number if possible), that would be great. I'll try to take a look at some point this week. I'm guessing the status icons you opened a second issue for a related (probably huge but hidden by overflow).

**Comment by Barina** [comment]
I knew I forgot something!
Yes I tried it on MS Edge 100.0.1185.44 (Official build) (64-bit) on Windows 11 Pro 210604-1628
I didn't tried different OS\browsers yet..
Thanks!

**Comment by Barina** [comment]
I've added:
`max-width: 16px;`  to 'a img, :link img, :visited img` (line 2)
`min-width: 16px;` to `#desktopFooter img` (line 667)
In `private/css/style.css`
Seems to solve the problem. at least in M$ edge :)

**Comment by crash0verride11** [comment]
I think some of this may be related to cacheing as I had the same problem with chrome when I was trimming away unnecessary CSS (I actively removed the lines you noted) but they started loading correctly.

I've incorporated a version of these changes adding the CSS back in though, hopefully reducing issues.
